name: Deploy on Push to Main

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@51.79.181.234 << 'EOF'
          cd /www/wwwroot/link.id

          echo "[github-actions] >> Pulling latest changes from main branch..."
          echo "Would run: git pull origin dev"

          echo "[github-actions] >> Checking for dependency changes..."

          if git diff --name-only HEAD~1 HEAD | grep -qE 'package(-lock)?\.json'; then
            echo "[github-actions] >> Installing Node.js dependencies..."
            echo "Would run: npm install"
          else
            echo "[github-actions] >> No changes in Node.js dependencies."
          fi

          if git diff --name-only HEAD~1 HEAD | grep -qE 'composer\.(json|lock)'; then
            echo "[github-actions] >> Installing updated PHP dependencies..."
            echo "Would run: composer install"
          else
            echo "[github-actions] >> No changes in PHP dependencies."
          fi

          echo "[github-actions] >> Deployment completed successfully."
        EOF
